version: '3.3'

services:
    web:
        build:
            context: ./docker/web
            dockerfile: Dockerfile
        ports:
            - "8050:80"
        volumes:
            - .:/var/www/html
            - ./docker/web/etc/apache2:/etc/apache2
            - ./docker/web/etc/php:/usr/local/etc/php
        restart: always
